// Fetching data
export const FETCH_BG_DATA_REQUEST = 'FETCH_BG_DATA_REQUEST'
export const FETCH_BG_DATA_FAILURE = 'FETCH_BG_DATA_FAILURE'
export const FETCH_BG_DATA_SUCCESS = 'FETCH_BG_DATA_SUCCESS'
export const FETCH_BASAL_DATA_REQUEST = 'FETCH_BASAL_DATA_REQUEST'
export const FETCH_BASAL_DATA_FAILURE = 'FETCH_BASAL_DATA_FAILURE'
export const FETCH_BASAL_DATA_SUCCESS = 'FETCH_BASAL_DATA_SUCCESS'
export const FETCH_TB_DATA_REQUEST = 'FETCH_TB_DATA_REQUEST'
export const FETCH_TB_DATA_FAILURE = 'FETCH_TB_DATA_FAILURE'
export const FETCH_TB_DATA_SUCCESS = 'FETCH_TB_DATA_SUCCESS'

// Time
export const UPDATE_TIME = 'UPDATE_TIME'

// Bubble
export const RESET_BUBBLE = 'RESET_BUBBLE'
export const MOVE_BUBBLE = 'MOVE_BUBBLE'
export const UPDATE_BUBBLE = 'UPDATE_BUBBLE'

// Axes
export const UPDATE_TIME_AXIS = 'UPDATE_TIME_AXIS'
export const UPDATE_BG_AXIS = 'UPDATE_BG_AXIS'
export const UPDATE_BASAL_AXIS = 'UPDATE_BASAL_AXIS'

// Inner
export const UPDATE_INNER_BG_SIZE = 'UPDATE_INNER_BG_SIZE'
export const UPDATE_INNER_BASAL_SIZE = 'UPDATE_INNER_BASAL_SIZE'