// Fetching data
export const FETCH_DATA_BG = 'FETCH_DATA_BG';
export const FETCH_DATA_BG_PENDING = 'FETCH_DATA_BG_PENDING';
export const FETCH_DATA_BG_REJECTED = 'FETCH_DATA_BG_REJECTED';
export const FETCH_DATA_BG_FULFILLED = 'FETCH_DATA_BG_FULFILLED';
export const FETCH_DATA_PUMP = 'FETCH_DATA_PUMP';
export const FETCH_DATA_PUMP_PENDING = 'FETCH_DATA_PUMP_PENDING';
export const FETCH_DATA_PUMP_REJECTED = 'FETCH_DATA_PUMP_REJECTED';
export const FETCH_DATA_PUMP_FULFILLED = 'FETCH_DATA_PUMP_FULFILLED';
export const FETCH_DATA_TREATMENT = 'FETCH_DATA_TREATMENT';
export const FETCH_DATA_TREATMENT_PENDING = 'FETCH_DATA_TREATMENT_PENDING';
export const FETCH_DATA_TREATMENT_REJECTED = 'FETCH_DATA_TREATMENT_REJECTED';
export const FETCH_DATA_TREATMENT_FULFILLED = 'FETCH_DATA_TREATMENT_FULFILLED';
export const FETCH_DATA_HISTORY = 'FETCH_DATA_HISTORY';
export const FETCH_DATA_HISTORY_PENDING = 'FETCH_DATA_HISTORY_PENDING';
export const FETCH_DATA_HISTORY_REJECTED = 'FETCH_DATA_HISTORY_REJECTED';
export const FETCH_DATA_HISTORY_FULFILLED = 'FETCH_DATA_HISTORY_FULFILLED';

// Time
export const UPDATE_TIME = 'UPDATE_TIME';
export const UPDATE_TIMESCALE = 'UPDATE_TIMESCALE';
export const UPDATE_LAST_FETCH_TIME = 'UPDATE_LAST_FETCH_TIME';

// Bubble
export const RESET_BUBBLE = 'RESET_BUBBLE';
export const SHOW_BUBBLE = 'SHOW_BUBBLE';
export const HIDE_BUBBLE = 'HIDE_BUBBLE';
export const MOVE_BUBBLE = 'MOVE_BUBBLE';
export const UPDATE_BUBBLE = 'UPDATE_BUBBLE';
export const RESIZE_BUBBLE = 'RESIZE_BUBBLE';

// Axes
export const UPDATE_TIME_AXIS = 'UPDATE_TIME_AXIS';
export const UPDATE_BG_AXIS = 'UPDATE_BG_AXIS';
export const UPDATE_BASAL_AXIS = 'UPDATE_BASAL_AXIS';

// Inner
export const UPDATE_INNER_BG_SIZE = 'UPDATE_INNER_BG_SIZE';
export const UPDATE_INNER_BASAL_SIZE = 'UPDATE_INNER_BASAL_SIZE';