const DEFAULT_NEGATIVE_TIMED_DATA = {
    time: -1,
    value: -1,
}

const DEFAULT_ZERO_TIMED_DATA = {
    time: -1,
    value: 0,
}

const DEFAULT_EMPTY_STRING_TIMED_DATA = {
    time: -1,
    value: '',
}

export const DEFAULT_BG = DEFAULT_NEGATIVE_TIMED_DATA
export const DEFAULT_DBG = DEFAULT_NEGATIVE_TIMED_DATA
export const DEFAULT_BG_TREND = DEFAULT_EMPTY_STRING_TIMED_DATA
export const DEFAULT_BASAL = DEFAULT_NEGATIVE_TIMED_DATA
export const DEFAULT_ISF = DEFAULT_NEGATIVE_TIMED_DATA
export const DEFAULT_CSF = DEFAULT_NEGATIVE_TIMED_DATA
export const DEFAULT_IOB = DEFAULT_ZERO_TIMED_DATA
export const DEFAULT_COB = DEFAULT_ZERO_TIMED_DATA
export const DEFAULT_RESERVOIR = DEFAULT_NEGATIVE_TIMED_DATA
export const DEFAULT_PUMP_BATTERY = DEFAULT_NEGATIVE_TIMED_DATA
export const DEFAULT_CGM_BATTERY = DEFAULT_NEGATIVE_TIMED_DATA
export const DEFAULT_SENSOR_AGE = DEFAULT_NEGATIVE_TIMED_DATA
export const DEFAULT_CANULA_AGE = DEFAULT_NEGATIVE_TIMED_DATA