import * as DataTypes from 'constants/DataTypes'

const NEGATIVE_TIMED_VALUE = new DataTypes.TimeData(-1)
const ZERO_TIMED_VALUE = new DataTypes.TimeData(0)
const EMPTY_STRING_TIMED_VALUE = new DataTypes.TimeData('')

export const DEFAULT_BG = ZERO_TIMED_VALUE
export const DEFAULT_DBG = ZERO_TIMED_VALUE
export const DEFAULT_BG_TREND = EMPTY_STRING_TIMED_VALUE
export const DEFAULT_BASAL = NEGATIVE_TIMED_VALUE
export const DEFAULT_ISF = NEGATIVE_TIMED_VALUE
export const DEFAULT_CSF = NEGATIVE_TIMED_VALUE
export const DEFAULT_IOB = NEGATIVE_TIMED_VALUE
export const DEFAULT_COB = NEGATIVE_TIMED_VALUE
export const DEFAULT_RESERVOIR = NEGATIVE_TIMED_VALUE
export const DEFAULT_PUMP_BATTERY = NEGATIVE_TIMED_VALUE
export const DEFAULT_CGM_BATTERY = NEGATIVE_TIMED_VALUE
export const DEFAULT_SENSOR_AGE = NEGATIVE_TIMED_VALUE
export const DEFAULT_CANULA_AGE = NEGATIVE_TIMED_VALUE